name: Sync AS EAD

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    environment: base

    steps:
      - name: Check out development
        uses: actions/checkout@v6
        with:
          ref: development

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Sync data from S3
        run: |
          aws s3 sync \
            s3://rac-prod-as-export/ead/ \
            ./ead/ \
            --delete

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: data-updates
          base: development
          delete-branch: true
          commit-message: "chore: update EAD data"
          title: "chore: update EAD data"
          body: |
            Updates the contents of `ead/` from AWS.

            This pull request was generated automatically.
